### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by aperrin66** [nansencenter/django-geo-spaas-rest-api#2]
Write unit tests for the existing API before developing it further.

**Comment by akorosov** [comment]
* Add runtests.py (similar to django-geo-spaas)
* Add tests dir with settings.py and urls.py (similar to django-geo-spaas)
* Add tests to django-geo-spaas-rest-api/geospaas_rest_api/tests.py
* Use client to simulate post and get requests:
https://docs.djangoproject.com/en/3.0/topics/testing/tools/

**Comment by aanersc** [comment]
@akorosov 
Please have a look at 1e4b25d. It is ready.
